version: "3.7"

services:
  acmevita-db:
    container_name: acmevita-db
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/create-multiple-postgres-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgres-databases.sh
    networks:
      - acmevita-network
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  acmevita-web:
    container_name: acmevita-web
    build: .
    restart: always
    volumes:
      - .:/usr/src/project/
    networks:
      - acmevita-network
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
    depends_on:
      - acmevita-db

volumes:
  postgres_data:
networks:
  acmevita-network: